services:
  php:
    image: php:8.2-cli
    container_name: pdf_from_md_php
    working_dir: /app
    volumes:
      - .:/app
    build:
      context: .
      dockerfile: Dockerfile
    command: php -S 0.0.0.0:8000 -t bin
    ports:
      - "8000:8000"
    environment:
      PHP_MEMORY_LIMIT: 512M

  composer:
    image: composer:2
    container_name: pdf_from_md_composer
    working_dir: /app
    volumes:
      - .:/app
    command: install

  phpunit:
    image: php:8.2-cli
    container_name: pdf_from_md_phpunit
    working_dir: /app
    volumes:
      - .:/app
    command: ./vendor/bin/phpunit

  nginx:
    image: nginx:alpine
    container_name: pdf_from_md_nginx
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - .:/app
    depends_on:
      - php
